---
hyperparams:
  nodes_per_layer: [100, 50, 25, 10]
  batch_size: 20
  epochs: 10
  lr: 0.0001
  momentum: 0.9
  nesterov: false

inputs:
  cleaned: "./grouped_data.csv"
  outcomes: "./data/training_data/PreFer_train_outcome.csv"
  test: "./grouped_data.csv"
  test_outcomes: "./data/training_data/PreFer_train_outcome.csv"